{% set name = "opentelemetry-instrumentation-jinja2" %}
{% set version = "0.46b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_jinja2-{{ version }}.tar.gz
  sha256: c696cdc6cf9f23d9dfe0d6bb90d03d534d1c296fa806b9735655fbcca9925927

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.46b0
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-jinja2
  summary: OpenTelemetry jinja2 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
