{% set name = "opentelemetry-instrumentation-jinja2" %}
{% set version = "0.38b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_jinja2-{{ version }}.tar.gz
  sha256: 82558c6df81bd0678022c4f7c74cc04606d0a4544d8118657958a53502757a37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.38b0
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-jinja2
  summary: OpenTelemetry jinja2 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
