{% set name = "opentelemetry-instrumentation-jinja2" %}
{% set version = "0.53b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_jinja2-{{ version }}.tar.gz
  sha256: e5e8a4aed9b3d0abbbf3ad14fb6ebb7ee0cb7a5cfa8e098695cb27a5b42cfcbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.53b0
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-jinja2 
    # - markupsafe ==2.0.1
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7
    # - jinja2 <4.0,>=2.7

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-jinja2
  summary: OpenTelemetry jinja2 instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
